version: '3.3'

services:
  api:
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      MONGO_URL: mongodb://mongo:27017/
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    logging:
      driver: none
    ports:
      - 27017:27017
